Enrollment nnumber - 240840116004

practical 3 : Apply filtering,sorting , aggregation and groupby operatons on real world dataset using pandas

In [ ]:
import pandas as pd
data = { "Emp_id" : [101,102,103,104,105,106,107,108],
         "name" : ["rahul","priya","amit","riya","karan","neha","vivek","pooja"],
         "department" : ["IT","HR","IT","Finance","HR","Finance","IT","HR"],
         "city" : ["Surat","Navsari","Surat","Valsad","Surat","Navsari","Valsad","Surat"],
         "salary" :[45000,38000,52000,48000,40000,51000,60000,42000],
         "Expereince" : [2,1,5,4,2,6,8,3]
         }
df = pd.DataFrame(data)
print(df)

   Emp_id   name department     city  salary  Expereince
0     101  rahul         IT    Surat   45000           2
1     102  priya         HR  Navsari   38000           1
2     103   amit         IT    Surat   52000           5
3     104   riya    Finance   Valsad   48000           4
4     105  karan         HR    Surat   40000           2
5     106   neha    Finance  Navsari   51000           6
6     107  vivek         IT   Valsad   60000           8
7     108  pooja         HR    Surat   42000           3

step 1

In [ ]:
df

   Emp_id   name department     city  salary  Expereince
0     101  rahul         IT    surat   45000           2
1     102  priya         HR  Navsari   38000           1
2     103   amit         IT    surat   52000           5
3     104   riya    Finance   Valsad   48000           4
4     105  karan         HR    surat   40000           2
5     106   neha    Finance  Navsari   51000           6
6     107  vivek         IT   Valsad   60000           8
7     108  pooja         HR    Surat   42000           3

step 2 : display employees from it departement

In [ ]:
df[df["department"]=="IT"]

   Emp_id   name department    city  salary  Expereince
0     101  rahul         IT   surat   45000           2
2     103   amit         IT   surat   52000           5
6     107  vivek         IT  Valsad   60000           8

In [ ]:
df[df["Emp_id"]==103]

   Emp_id  name department   city  salary  Expereince
2     103  amit         IT  surat   52000           5

display employee whoise salary is greater than 50000

In [ ]:
df[df['salary']>50000]

   Emp_id   name department     city  salary  Expereince
2     103   amit         IT    surat   52000           5
5     106   neha    finance  Navsari   51000           6
6     107  vivek         IT   Valsad   60000           8

display emp-loyees from surat

In [ ]:
df[df['city']=="surat"]

   Emp_id   name department   city  salary  Expereince
0     101  rahul         IT  surat   45000           2
2     103   amit         IT  surat   52000           5
4     105  karan         HR  surat   40000           2

APPLY MULTIPLE CONDITIONS : display employees from the it department , having salary greater than 50000

In [ ]:
df[(df["department"]=="IT")&(df["salary"]>50000)]

   Emp_id   name department    city  salary  Expereince
2     103   amit         IT   Surat   52000           5
6     107  vivek         IT  Valsad   60000           8

sort salary in assecnding order

In [ ]:
df.sort_values(by="salary", ascending=True)

   Emp_id   name department     city  salary  Expereince
1     102  priya         HR  Navsari   38000           1
4     105  karan         HR    Surat   40000           2
7     108  pooja         HR    Surat   42000           3
0     101  rahul         IT    Surat   45000           2
3     104   riya    Finance   Valsad   48000           4
5     106   neha    Finance  Navsari   51000           6
2     103   amit         IT    Surat   52000           5
6     107  vivek         IT   Valsad   60000           8

sort salary in descending order

In [ ]:
df.sort_values(by="salary",ascending=False)

   Emp_id   name department     city  salary  Expereince
6     107  vivek         IT   Valsad   60000           8
2     103   amit         IT    surat   52000           5
5     106   neha    finance  Navsari   51000           6
3     104   riya    Finance   Valsad   48000           4
0     101  rahul         IT    surat   45000           2
7     108  pooja         HR    Surat   42000           3
4     105  karan         HR    surat   40000           2
1     102  priya         HR  Navsari   38000           1

sort by deparetmenmt and salary

In [ ]:
df.sort_values(by=["department","salary"] , ascending=[True,False])

   Emp_id   name department     city  salary  Expereince
5     106   neha    Finance  Navsari   51000           6
3     104   riya    Finance   Valsad   48000           4
7     108  pooja         HR    Surat   42000           3
4     105  karan         HR    surat   40000           2
1     102  priya         HR  Navsari   38000           1
6     107  vivek         IT   Valsad   60000           8
2     103   amit         IT    surat   52000           5
0     101  rahul         IT    surat   45000           2

step 4 : perform aggregation

In [ ]:
calculate the total salary of all the employee

In [ ]:
df["salary"].sum()

np.int64(376000)

find the highest salary

In [ ]:
df["salary"].max()

60000

find lowest salary

In [ ]:
df["salary"].min()

38000

count employees

In [ ]:
df["Emp_id"].count()

np.int64(8)

step 5 - perform groupby operations

Average salary department-wise
#group employees based on department
# calculate the average salary of each department

In [ ]:
df.groupby("department")["salary"].mean()

department
Finance    49500.000000
HR         40000.000000
IT         52333.333333
Name: salary, dtype: float64

min salary department wise

In [ ]:
df.groupby("department")["salary"].min()

department
Finance    48000
HR         38000
IT         45000
Name: salary, dtype: int64

count employees department wise

In [ ]:
df.groupby("department")["Emp_id"].count()

department
Finance    2
HR         3
IT         3
Name: Emp_id, dtype: int64

max salary

In [ ]:
df.groupby("department")["salary"].max()

department
Finance    51000
HR         42000
IT         60000
Name: salary, dtype: int64

total salary department wise

In [ ]:
df.groupby("department")["salary"].sum()

department
Finance     99000
HR         120000
IT         157000
Name: salary, dtype: int64

average salary city wise

In [ ]:
df.groupby("city")["salary"].mean()

city
Navsari    44500.0
Surat      44750.0
Valsad     54000.0
Name: salary, dtype: float64

step 6 : Multiple agrregation functions

In [ ]:
df.groupby("department")["salary"].agg(["count", "sum", "min", "max", "mean"])

            count     sum    min    max          mean
department
Finance         2   99000  48000  51000  49500.000000
HR              3  120000  38000  42000  40000.000000
IT              3  157000  45000  60000  52333.333333

step 7 - save the result

In [ ]:
df.to_csv("Emp_iddata.csv" , index=False)
print("dataset saved succesfully ")

dataset saved succesfully

step 8 dowload csv file

In [ ]:
df.to_csv("Emp_Id.csv",index=False)
from google.colab import files
files.download("Emp_Id.csv")